<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
//    'registered user information' => '注册用户信息',
//    'registered user list' => '注册用户列表',
//    'menu' => '菜单',
//    'backstage management system' => '后台管理系统',
//    'home page' => '主页',
//    'user management' => '用户管理',
//    'control panel' => '控制面板',
//    'Authority Management' => '权限管理',
//    'Administrator List' => '管理员列表',
//    'administrator' => '管理员',
//    'Permission List' => '权限列表',
//    'Role List' => '角色列表',
//    'Order Management' => '订单管理',
//    'Order List' => '订单列表',
//    'Management' => '管理',
//    'May you happy every day!' => '愿你开心每一天！',
//    'log out' => '退出',
//    'log in' => '登录',
//    'online' => '在线',
//    'add' => '添加',
//    'user name' => '用户名',
//    'password' => '密码',
//    'nickname' => '昵称',
//    'real name' => '真实姓名',
//    'mobile' => '手机',
//    'role' => '角色',
//    'creation time' => '创建时间',
//    'Last login time' => '最后登录时间',
//    'Last login IP' => '最后登录ip',
//    'status' => '状态',
//    'operation' => '操作',
//    'normal' => '正常',
//    'forbidden' => '禁用',
//    'Are you sure you want to disable these accounts?' => '确定禁用？',
//    'Are you sure you want to remove disable these accounts?' => '确定解除禁用？',
//    'Remove disable' => '解禁',
//    'edit' => '编辑',
//    'delete' => '删除',
//    'go back' => '返回',
//    'submit' => '提交',
];
