<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '注册用户信息' => 'registered user information',
    '注册用户列表' => 'registered user list',
    '菜单' => 'menu',
    '后台管理系统' => 'backstage management system',
    '主页' => 'home page',
    '用户管理' => 'user management',
    '控制面板' => 'control panel',
    '控制台' => 'console',
    '权限管理' => 'Authority Management',
    '管理员列表' => 'Administrator List',
    '管理员' => 'administrator',
    '权限列表' => 'Permission List',
    '角色列表' => 'Role List',
    '订单管理' => 'Order Management',
    '订单列表' => 'Order List',
    '管理' => 'Management',
    '愿你开心每一天！' => 'May you happy every day!',
    '退出' => 'log out',
    '登录' => 'log in',
    '在线' => 'online',
    '添加' => 'add',
    '用户名' => 'user name',
    '密码' => 'password',
    '昵称' => 'nickname',
    '真实姓名' => 'real name',
    '手机' => 'mobile',
    '角色' => 'role',
    '创建时间' => 'creation time',
    '最后登录时间' => 'Last login time',
    '最后登录ip' => 'Last login IP',
    '状态' => 'status',
    '操作' => 'operation',
    '正常' => 'normal',
    '禁用' => 'forbidden',
    '确定禁用？' => 'Are you sure you want to disable these accounts?',
    '确定解除禁用？' => 'Are you sure you want to remove disable these accounts?',
    '解禁' => 'Remove disable',
    '编辑' => 'edit',
    '删除' => 'delete',
    '返回' => 'go back',
    '提交' => 'submit',
    '订单号' => 'order number',
    '用户ID' => 'user id',
    '手机号' => 'mobile',
    '第三方交易号' => 'third trade number',
    '订单价格' => 'order price',
    '课程名称' => 'course name',
    '用户详情' => 'user details',
    '联系电话' => 'phone',
    '权限' => 'authority',
    '描述' => 'description',

];
