<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */
return [
    'color' => null,
    'interactive' => true,
    'help' => null,
    'sourcePath' => __DIR__ . DIRECTORY_SEPARATOR . '..',#修改为待翻译目录
//    'sourcePath' => '@yii',#修改为待翻译目录
    'messagePath' => 'backend/messages',
    'languages' => ['en-US','zh-CN'],
    'translator' => 'Yii::t',
    'sort' => false,
    'overwrite' => true,
    'removeUnused' => false,
    'markUnused' => true,
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/BaseYii.php',
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'php',//默认生成时，是基于文件翻译，db默认为数据库
    'db' => 'db',
    'sourceMessageTable' => '{{%source_message}}',//待翻译消息表
    'messageTable' => '{{%message}}',//翻译后消息表
    'catalog' => 'messages',
    'ignoreCategories' => [],
];
